services:
  mt5-tester:
    build:
      context: .
      dockerfile: Dockerfile
    image: mt5-docker
    container_name: mt5-tester
    volumes:
      - ./config:/config
      - ./data-tester:/data
      - ./config.yaml:/data-tester/config/config.yaml
    ports:
      - 3001:3000
      - 8002:8001
    env_file:
      - .env
    environment:
      - UPDATE_PACKAGES=false
      - MT5_MODE=tester
    security_opt:
      - seccomp=unconfined
      - label=disable
